# Generated by Django 4.1.5 on 2023-08-06 06:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cookie_stand", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Thing",
            new_name="CookieStand",
        ),
    ]
